### ISSUE TITLE
Support older browsers

### ISSUE THREAD

**Issue by volantwish** [findthemasks/findthemasks#166]
Followup to #66  to add support for older browsers (https://caniuse.com/#feat=arrow-functions)

**Comment by patricknelson** [comment]
Template literals as well, if supporting IE11: https://caniuse.com/#feat=template-literals 

Would be great to have analytics stats on this. I know on our websites we typically drop support for browsers that are at or below 2%-3% market share (just to save on dev resources).

**Comment by vdalal** [comment]
Related to #66
Site renders fine with:
* Microsoft Edge 80.0.xyz/Windows 10

**Comment by vdalal** [comment]
Filters:
* "Zip Code": works
* "City, State": works
* "Use my location": does not work
* "Use my location": option disappears after one clicks on it
* "State": works
* "By Accepted Items": works

Tested with Microsoft Edge 80.0.xyz/Windows 10

**Comment by r-pop** [comment]
Keep in mind that IE and older Edge will be overrepped in healthcare. I have seen Win95 in hospitals when there as a patient, even in tech-centric Seattle.

**Comment by saikatbhadra** [comment]
Putting the same caveat as @r-pop - Healthcare workers will be on more archaic systems. However, as long as they can go to to the site and fill out the form their main use case will be handled.

**Comment by saikatbhadra** [comment]
Here are the browser stats. I was noticing some patterns changing (for example desktop usage going up) so please access GA for the latest stats:

Chrome version stats:
![Screen Shot 2020-03-31 at 4 22 09 PM](https://user-images.githubusercontent.com/2250961/78084018-f954ca80-736b-11ea-99f7-5f1881bc75ec.png)

Safari stats (what is 604???):
![Screen Shot 2020-03-31 at 4 24 30 PM](https://user-images.githubusercontent.com/2250961/78084090-2ef9b380-736c-11ea-9b6f-5ac11e6adba2.png)

Firefox stats:
![Screen Shot 2020-03-31 at 4 26 25 PM](https://user-images.githubusercontent.com/2250961/78084192-65cfc980-736c-11ea-9879-497ac244740a.png)

**Comment by saikatbhadra** [comment]
Edge stats:

![Screen Shot 2020-03-31 at 4 29 45 PM](https://user-images.githubusercontent.com/2250961/78084376-e1317b00-736c-11ea-8341-bf93c4d92ac5.png)

IE stats:
![Screen Shot 2020-03-31 at 4 29 45 PM](https://user-images.githubusercontent.com/2250961/78084413-fad2c280-736c-11ea-9bdb-2fac9c782684.png)

**Comment by saikatbhadra** [comment]
So the only common browsers that look weird to me are:
* Safari 604 
* Edge 18 

I'm not familiar with either of those browsers. Are they modern?

**Comment by patricknelson** [comment]
@r-pop that may be true (I actually expect that too), interestingly enough the analytics doesn't reflect that. It's possible that there are factors skewing it away from what we expect! In fact, this could be a hint that there are deeper issues, e.g.

1. Maybe they're encountering fatal JS errors which are preventing Google Analytics from loading, skewing the stats.
2. Maybe they have security software that is filtering it out (unlikely, but feasible, as some may have interstitial proxies, would require that they intercept SSL connections and install root CA certificate on browsers, which some corps do but usually they don't MiTM their own browsers)

I'm leaning toward #1; do you have server logs that you can check? Go oldschool and run something likw AwStats which can analyze server logs to determine more accurately the amount of old browsers your seeing, in case the newfangled arrow functions and module expressions are causing JS to terminate early, resulting in failed analytics (note that the `<noscript>` will still fail to fire since that can only happen if JS is actually disabled).
