### ISSUE TITLE
How does a hospital turn off the flow of masks?

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#17]
If too many people show up/obstruct operations or cause trouble somehow, how do we shut off the flow of people quickly?

The contact email at the bottom of the page is a good start, but is there anything further we can do, so that @r-pop doesn't need to be awake at all-hours?

**Comment by r-pop** [comment]
This is a problem that would be wonderful to encounter, but is unlikely. Hospitals have security and can turn people away if needed. But right now they need PPE.

**Comment by 4kbt** [comment]
"First, do no harm" is important -- if we somehow wind up compromising a hospital's essential function, then we aren't helping the problem any more... 

Also, as I've learned from past experience assisting government function, frequently there is an office that is already working *really* hard to do the thing that needs doing (PPE--> hospitals in this case). We should try to aid them as much as we can, rather than duplicate their functionality. Local health departments, for example, may be able to coordinate donations and allocate them where they are needed most.

**Comment by r-pop** [comment]
Do you have a suggestion for addressing this issue?

Right now I get notified immediately on email to contact@, and can take a listing down in minutes. You are right that my SLA is ~8 hours because I will sleep sometimes. :) 

In the next version of the system, we will have a pipeline pulling regularly from a sheet (this is the form response sheet, not the comprehensive dataset sheets you posted). The sheet will have a publish column, and we will be able to unpublish a listing by modifying that column. That's easier than manually editing and deploying HTML, and we can staff the contact email address to make sure someone is available across timezones. This should be up within the next few days.

**Comment by leee** [comment]
In general, hospitals aren't the only groups with shortages. If they have an overflowing bounty, that will likely go to other neighboring hospitals (especially in high density areas), or to EMS agency(ies) serving that area and/or hospital. Beyond that, there's a lack of PPE available for healthcare public-safety adjacents like FDs and PDs.

**Comment by spitznagel** [comment]
I believe this issue has been resolved and can be closed. It appears resolved in the latest Google Form:

![image](https://user-images.githubusercontent.com/8340647/77851844-19c82d80-7190-11ea-94e0-8cd27d764b77.png)
