### ISSUE TITLE
Map loading slowly - add progress indicator

### ISSUE THREAD

**Issue by r-pop** [findthemasks/findthemasks#208]
we've reached a point where the map takes a noticable second to display on pageload. Can we as a stopgap put a "Loading..." indicator in its place

The text "Loading..." is fine

**Comment by r-pop** [comment]
This is what it looks like while loading. It looks like there is no data. We need to say "Loading list of donation sites..."
![slowload](https://user-images.githubusercontent.com/11252938/77581197-81356300-6e9a-11ea-8748-bfce960af80e.png)

**Comment by Panometric** [comment]
A few suggestions:
1. At 1400+ datapoints, it is never going to render quickly. How about using the attached image as a place holder until it renders?  We could also make this image fuzzy. 
![image](https://user-images.githubusercontent.com/716218/77599021-a5a43600-6ec0-11ea-99cc-5b2ff31988b2.png)

2. There is a usage limit 500 requests per second (QPS). If the site is too busy, the requests will just fail. So maybe put the actual map under a search button?
https://developers.google.com/maps/documentation/embed/usage-and-billing

**Comment by patricknelson** [comment]
After further analysis, it appears a majority of the latency appears to be in network overhead. Specifically, the downloading, decompressing and parsing the https://findthemasks.com/data.json file (page is able to runder while XHR kicks off in another thread to pull that file down) which is why we still see the page waiting for it to DL and doesn't seem to have anything to do with the map.

Turns out there may not be a dramatic difference with vs. without Google Maps, see below (alternating between https://findthemasks.com/give.html vs. https://findthemasks.com/give.html?hide-map=true. In this case, if `hide-map=true` it completely avoids initializing Google Maps and had similar delay. 

Still digging into this.... see below, though.

![2020-03-25_17-54-25](https://user-images.githubusercontent.com/4269377/77599647-a211ae80-6ec2-11ea-8c18-97e773a8b7ee.gif)

**Comment by patricknelson** [comment]
Working on wrapping this up.

**Comment by patricknelson** [comment]
Ok fix here: #216
