### ISSUE TITLE
Backing up raw Google Form-input to a second location

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#209]
At the moment, the intake form directs data to Form Responses 1, and we edit it directly from there. 

In particular, we are editing the "address" field directly, and we're doing it to every row. If the initial information is lost, we will never get it back.

Is there a way to save a copy of the raw form-output as it lands in Form Responses?

**Comment by Panometric** [comment]
A few ways we might do this using App Script:
1. onFormSubmit would fire every time a new form is added. We could append these to another sheet. 
https://stackoverflow.com/questions/17992718/how-to-get-onformsubmit-to-trigger-automatically
2. onEdit could trigger anytime a sheet cell is changed, so that you could capture the old value and new value. We could append both to another sheet so that all changes were searchable and attributed to the editor.  https://developers.google.com/apps-script/guides/triggers/events

**Comment by 4kbt** [comment]
This is done. All entries land in en, which backs things up. Turns out, the Google Form also backs this up.

All is well. Also, the autobackups preserve Sheet state.

Bug is tostada.
