### ISSUE TITLE
New York City is a special place -- Google-Sheet expert needed.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#218]
Early on, the #data team began aggregating the five boroughs of NYC (Bronx , Brooklyn, Queens, Manhattan, Staten Island ), in the city field. 

In order to help all of the NYC entries together alphabetically, we decided to change 

The Bronx or Bronx --> New York - Bronkx
Brooklyn --> New York - Brooklyn
Queens --> New York - Queens
Manhattan --> New York - Manhattan
Staten Island ....  has never come up. Only entry is a doctor at Staten Island Hospital who lives in NJ.

Could this be scripted? (or, if it is nerfing up the auto-gen system, reverted by a script?)

Extra wrinkle: Flushing NY  is a subset of Queens NY, but gets its own (dual) postal address.

**Comment by susanashlock** [comment]
A proposal of how to do this:

- Add a column next to the existing city column.  Set row 2 for this column to 'autoCity'
- Use a formula that points to an Apps Script to populate the column based on the logic described by 4kbt.
- Set row 2 for this column to 'city'.  The scripts and website will then read from this column.
- Set row 2 for the existing city column to orig_city.
- Optional (if moderators want it): hide the orig_city column if it makes your lives easier.

Things to test:  Make sure that address autogeneration still works for these rows.

**Comment by crayne** [comment]
I'm new here, and I have lived in or near NYC my whole life.

 I don't know how the address generation works, but there are some additional issues with the resulting list.  For example, there is a Brooklyn section and a New York - Brooklyn section.  The same is true for the Bronx and Queens.  There are two New York - Manhattan sections. There are 2 New York sections and a NY section. And as mentioned above, each Queens sub-entity has its own section.  I think everything in Queens should be under "New York - Queens".

I could fix all this manually, or could take a crack at changing the existing automation if I can get some information on how it works.

**Comment by 4kbt** [comment]
Awesome, @crayne. (We're all new here :). ) We've needed a native New Yorker to break the tie. 

I just manually (hopefully) updated all of them to New York - Brooklyn style. 

If you're able to manually update the NY and New York sections manually to their respective boroughs, that'll get us close.  There is probably a trailing space that makes the Manhattan sections different.

I'll see if we can ping our AppScript jockeys ( ask Albert and Susan on Slack for help getting started with that, if you want to dig in ) to automate it. 

Thank you, beloved tiebreaker :)!

**Comment by crayne** [comment]
OK, but how do you access the spreadsheet?

**Comment by crayne** [comment]
Actually, I think I need a copy of the spreadsheet on Google Sheets that I can alter and test by changing my branch code to point to it.

**Comment by crayne** [comment]
@susanashlock @awong-dev I'd like to do this manually first -- then maybe automate it.  Could someone make a copy of the spreadsheet that I can tinker with? Thanks.

**Comment by crayne** [comment]
So I've done what @4kbt proposed manually, and I've also done the following:
NY -> New York - Manhattan
NewYork -> New York - Manhattan
Astoria -> New York - Queens
Bayside -> New York - Queens
Elmhurst -> New York - Queens
Flushing -> New York - Queens
Forest Hills -> New York - Queens
Howard Beach -> New York - Queens
Jamaica -> New York - Queens
Ridgewood -> New York - Queens
Woodside -> New York - Queens

There are probably other Queens "neighborhoods" which need to be changed, but since they haven't appeared yet I think they can wait for the automation step

**Comment by crayne** [comment]
@susanashlock I've copied the steps from your comment above here:

1. Add a column next to the existing city column. Set row 2 for this column to 'autoCity'
2. Use a formula that points to an Apps Script to populate the column based on the logic described by 4kbt.
3. Set row 2 for this column to 'city'. The scripts and website will then read from this column.
4. Set row 2 for the existing city column to orig_city.

Am I correct in thinking that this all must be done manually (except for the running of the script) in order to "fix" the city names.  Then we (probably I) would do it periodically?
I wonder if there is a way to set up the form to allow only the city names that we want?
Or could it be done in the spreadsheet publishing step?
Both these ways would be fully automated.
Thank you for any insight you can provide.

**Comment by crayne** [comment]
This is now live.

**Comment by nburt** [comment]
🎉
