### ISSUE TITLE
Should we align our imagery and terminology for PPE with getusppe?

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#336]
![Screen Shot 2020-03-28 at 11 52 54 PM](https://user-images.githubusercontent.com/2250961/77843176-853ddb00-714f-11ea-8e53-09b52a249838.png)

vs

![Screen Shot 2020-03-28 at 11 55 45 PM](https://user-images.githubusercontent.com/2250961/77843194-aa324e00-714f-11ea-9619-b371d44ddaab.png)

**Comment by vdalal** [comment]
Agree

* Atleast align the verbiage so it is consistent
* Align the Google Forms (for the items that are common at the moment) so it is consistent too

**Comment by r-pop** [comment]
It is good info but someone needs to do some ux work to fit it into our design. Form text is fairly aligned, though includes other emergent categories as well. 

I am not viewing perfect alignment as necessary because the form users (healthcare workers) and folks who need PPE edu are different user groups.
