### ISSUE TITLE
Automatic residental-address detection

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#391]
It would be helpful to have automatic residential-address detection. @4kbt has explored SmartyStreets capabilities (at the suggestion of @marcuscollins) , and it looks plenty capable for our needs.

Why is it useful? Many of our recipients list residential addresses. Reasons vary, but they include increasing accessibility to the community, making drop-off safer for everyone, or perhaps avoiding employer restrictions on PPE donations.

In any case, it would be useful to surface a small note on residential donations like : "This appears to be a residential address. Many legitimate recipients list a home address to increase accessibility to the community."  or some such, just so a donor is not confused by "NYC Hospital" appearing in New Jersey, when in fact it is a doctor who works at NYC Hospital making the request.

**Comment by 4kbt** [comment]
We have attempted to do this detection by hand, but it takes too much time for us to do it with our current level of moderator support.

**Comment by saikatbhadra** [comment]
@4kbt - were you able to secure free API access?

**Comment by saikatbhadra** [comment]
I reached out to lob.com and easypost who have address validation apis that can do the same thing.

**Comment by 4kbt** [comment]
Never heard back from them, which is a real bummer. They were super
responsive on their first interaction. They hand-processed our entire
dataset, recorded a movie...  really cool.

**Comment by 4kbt** [comment]
An update -- got a reply from SmartyStreets today. Following up.

**Comment by 4kbt** [comment]
Continued traction -- they're going to provision a findthemasks account with quota.

**Comment by 4kbt** [comment]
Nate Burt: Should these fields be added back to the spreadsheet or just needed in data.json?

Charlie Hagedorn :
We'd want to add them to the spreadsheet (and perhaps many of the other SmartyStreets fields).   I've coordinated unlimited SmartStreets API calls for the next three months, and have an account ready to go. I just don't have the dev knowledge necessary to efficiently make it all go.

Have to make sure that the Sheet doesn't exceed 5 million cells, too. (probably not a problem, but the SmartyStreets data are rich).

The simplest approach is apt to be asking for a full smarty-streets dump for every Final Address into an independent tab, then pulling the columns we need into Combined for moderator use and packaging into data.json.

**Comment by 4kbt** [comment]
Necessary credentials are in dev-secrets.

**Comment by nburt** [comment]
Currently, the US has a cloud function called "smarty_streets_analysis" to look up smarty streets data for an address and write it to a separate tab in sheets. 

1. Update this cloud function so that it also adds the "rdi" column to the US Combined tab.
2. On the FE, if the rdi column is "Residential" add "Residential Address. (why residential?)" to the listing + infowindow popup. "why residential?" should link to a popover with a title of "Why residential" and a body of: 

"About 15% of our recipients list home addresses. This may be because it is safer/easier for donors to drop off at a nearby location, because their office hours are limited, or because they are having trouble getting PPE at work.

If you prefer to donate directly to a healthcare institution, please select another entry from among our thousands of recipients in need!"

**Comment by nburt** [comment]
Closing since the US is live, opened a separate issue for international: https://github.com/findthemasks/findthemasks/issues/762

**Comment by 4kbt** [comment]
So good.
