### ISSUE TITLE
Filter by Accepted Items doesn't work reliably (or at all for non-EN markets)

### ISSUE THREAD

**Issue by drwestco** [findthemasks/findthemasks#401]
Filter by Accepted Items does a string search on the Accepting field of each listing. Each item in the filter list uses a short name to search: n95s, masks, shields, booties, goggles, gloves, sanitizer, overalls, gowns, respirators

Obviously, in a non-EN market, when the Accepting field is in the local language, this match is never going to succeed.

Even in EN, it's not reliable. See the short name 'respirators' - this will match against both N95 masks/respirators and Advanced respirators and give mixed results. 'masks' will match both N95 masks and Surgical masks. etc.

Should we just get rid of this set of filters? Is there a better solution to apply these filters?

**Comment by linderr** [comment]
No, the filters are important - I was just going to create a separate Issue on them to actually add more categories to match what is being allowed through the Google Form. 

Especially now with more hospitals allowing homemade or 3D printed items, we need a way to display sites which have specify they allow for that. As much those in the maker space mean well, there are a lot of hospital policies and politics in place that prevent them, from a hospital management's perspective, to take on these items due to lack of iron-clad policies to take them on.

**Comment by linderr** [comment]
The issue I wanted to raise was that currently, there is no match between Google Form Items and Filter Items. That is like allowing the user to indicate they live in New York State and having no filter tile for "NY". Here is a screen grab from US-form items vs. US-filter list. Will it a separate issue for now as I think this can provide better usability of the data:
![image](https://user-images.githubusercontent.com/62862914/78110780-71dd7a80-73b0-11ea-9083-857cd0bec1ef.png)

**Comment by cgrayson** [comment]
From what I can tell, the problems described in this issue have already been fixed: the "filter by accepted items" values are more unique than what @drwestco described, and the values have been translated beyond EN. 

The issue raised by @linderr also seems resolved, as the filter-by items now match the request form: 

![issue401](https://user-images.githubusercontent.com/5596/78671305-bbdcc980-78a4-11ea-872e-76b638701912.jpg)
