### ISSUE TITLE
#i18n Copy Change for give.html [FTM-CA]

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#474]
Please change text under embed map on www.findthemasks.com/ca/give.html to:
"In collaboration with [#findthemasks](findthemasks.ca). Don't see your healthcare facility listed? <br>Fill in our PPE Request Form in [French](https://docs.google.com/forms/d/e/1FAIpQLSeM2Jt5zudVG9_IxCT0pXluTs4eHq7_p3X95klGCHSSSaDEFg/viewform) or [English](https://docs.google.com/forms/d/e/1FAIpQLSf5JAiAikzMEEw86eyjoRMH5AFlwaMrOmjjlr3vGcL5RrJt9A/viewform) to join the map!"

Many of our Canadian collaborators help us do data entry of the sites they have spend human hours cold-calling/emailing. I want to acknowledge this work and our collaboration, as well as link back to our homepage + CA-forms in both French and English.

**Comment by nburt** [comment]
@linderr currently we use the user's selected locale to determine whether or not we link CTAs to different locale specific forms. e.g. a user viewing the app in French would be redirected to the French form and a user viewing the app in English would be redirected to the English form. 

I believe this is a better experience for a user however it begs the question: Do our partners use the locale param to translate our give embed?

also note to self, revert fallback copy from this commit: https://github.com/findthemasks/findthemasks/commit/9c21c75a37c2a4a04329fa8a4b234d68d6da1623

**Comment by linderr** [comment]
I don't think our partners/collaborators in Canada have any ability to use the local param.

I only provide them the short script available in the Embed Wiki page. It results in this, for example: https://theppedrive.com/ppe-drive-listing

On my end, the default is English, always. Is it suppose to change for people viewing from Quebec to automatic French?

**Comment by linderr** [comment]
@nburt all they get is: 

> <iframe style="width: 100%; height: 800px; border: none;" src="https://findthemasks.com/ca/give.html?hide-list=true&state=ON"></iframe> to hide the filters and list as well as zoom in, in default view to Ontario

**Comment by nburt** [comment]
@linderr there are custom options, sounds like we need better documentation.

You can set the param in the src url with `locale=<locale code>`

`https://findthemasks.com/ca/give.html?hide-list=true&state=ON` will hide the list and filter to Ontario (as you have).

`https://findthemasks.com/ca/give.html?hide-list=true&state=ON&locale=fr` will hide the list, filter to Ontario, and translate to French. The button will also link to the French version of the Canadian form.

The rules for this are the following:

1. The country that the user is viewing has a set of forms, for Canada they are the default (English), English, and French.
2. If a user is viewing Canada in English, send them to the English form
3. If a user is viewing Canada in French, send them to the French form
4. If a user is viewing Canada in Portuguese, we don't have a translation in that language so send them to the default

I should also add that we do browser language detection. If the user's default browser setting is French (even if they don't explicitly choose "French" from the locale dropdown, we should default to French.

Does that make sense?

I think that leaving the CTA as "complete this form" is better for the user, and will also allow us to use a button instead of two links which would stand out more

**Comment by linderr** [comment]
@nburt I will add these extra parameters to the Wiki page for embedding tmr, thank you

**Comment by saikatbhadra** [comment]
Can I close this issue? Looks like it can be fixed with a url change.

**Comment by nburt** [comment]
Closing for now. @linderr if there are any canada-specific copy changes you want to make to the give page can you open a new issue and we can tackle there?

**Comment by linderr** [comment]
lmao, alright. The issue was not the language specificity per se. I just wanted light branding under the embed map but the previous system was fairly hard to make country-specific line edits. @maplebird said it may be easier in the coming days? I can wait

**Comment by nburt** [comment]
Yup it's easier now
