### ISSUE TITLE
Filtering on Idaho gets a hospital in Indiana

### ISSUE THREAD

**Issue by crayne** [findthemasks/findthemasks#509]
![image](https://user-images.githubusercontent.com/134657/78728461-6258b700-7905-11ea-9e4a-d90cf91e2619.png)

**Comment by saikatbhadra** [comment]
This is somehow fixed

**Comment by 4kbt** [comment]
Thanks for the catch!   It was somehow fixed by me (I hadn't seen the github issue, but rather caught it by skimming through every filter looking for mis-coded states). 

The problem is that users sometimes mis-select the state for a number of reasons. ID and IN are adjoining in the list, so that is probably what happened here. 

I can think of two possible quick fixes to the wider problem:

1) Building a spreadsheet tab/detector for occasions on which the Google-derived Final Address state differs from the user-entered state.

2) Using the state found from the Final Address field to seed the displayed state ID.   The Final Address field, at least when these errors come up, is often more correct than that which is submitted by the user.   Final Address is wrong sometimes, too, so we wouldn't be free of this kind of error if we went this route.

1 above, though, could be bolted in without interrupting/changing our workflow, and would speed up our detection of this kind of error. Right now, the best way to find them is by clicking sequentially through all of the state filters.  We get ~1 of these per ~200 submissions.

**Comment by 4kbt** [comment]
We might want to re-open this bug, or merge it with any related ones (I think there may be one or two more.)
