### ISSUE TITLE
[UI] Maps pins are layering over each other

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#510]
We have a use case for having multiple pins at the same location - usually multiple departments at hospitals each with their own PPE needs. In most of these cases the street address is the same so we have a case of multiple pins sitting on top of each other - we need to come up with a solution for our map (maybe stagger the pins).

**Comment by saikatbhadra** [comment]
@tinabeans - if you have free cycles can you weigh in on what we should do here (when we have multiple submissions for the same location due to different departments in a hospital)

**Comment by tinabeans** [comment]
@linderr - I remember you talking about a clever trick you did with... Tim Hortons? To solve this problem? Did I make this up. Was it really manual, though, and only an interim solution? Anyway...

My other thought @saikatbhadra is maybe we can just have a single aggregate pin, so that, for example, if you have 5 entries for one geolocation, when you click on it:

1. Scrolls to where all the entries are in the left sidebar and highlights all 5.
2. Pops up the little speech bubble on the map with all 5 locations inside it (scrollable)

Would that work?

**Comment by linderr** [comment]
@tinabeans yup - we still do that that hack! The logic is codeable but your way sounds good too.

Details to ensure are that the 5 entries you describe count as 5 sites vs. 1 site to reflect entry count versus "donation count" (boost those stats!)

Your idea would also require the match that @drwestco (Derek) suggested that a centred map view should also trigger a refresh of the left sidebar to only show listings within that map view :)
