### ISSUE TITLE
Reorder Filter Tiles to Match Form Order

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#567]
Hi Guys, thanks for adding new functionality to our dataset by doing the "homemasks" and "face shield - 3D printed/makerspace" filter tiles and all the logic behind that!

Can we reorder the tiles this way to help logical progression through the list? From:
N95s, Surgical masks, Face shields, Disposable booties, Safety goggles, Gloves, Gowns, Hand sanitizer, Disinfecting wipes, Handmade Masks, Face Shields - 3D-printed or makerspace, Thermometers, Walkie-talkies/baby monitors

To:
N95s, Surgical masks, **Handmade Masks**, Face shields, **Face Shields - 3D-printed or makerspace**, Disposable booties, Safety goggles, Gloves, Gowns, Hand sanitizer, Disinfecting wipes, Thermometers, Walkie-talkies/baby monitors

**Comment by ngottlieb** [comment]
What about alphabetical? We are not setup to do country-by-country ordering and I wouldn't want to really get into the ordering beyond a basic scheme (like alphabetical) without some sort of strong UX case for it.

**Comment by linderr** [comment]
@ngottlieb the proposed order is the same order they show up in all forms, regardless of language or country. This is the US form, for example. There is logical progression as ordered from most requested (N95) etc.
 
![image](https://user-images.githubusercontent.com/62862914/79178204-7135e280-7db9-11ea-90d8-8b73fec039a5.png)

**Comment by ngottlieb** [comment]
I'd be surprised if that list is actually ordered by most requested. For example, I doubt that "Face shields" and "Face Shields - 3D-printed or makerspace" are actually right next to each other in amount requested?  That is a UX change I could see making sense -- but that would explicitly *not* mean matching it to what's on the form, it would mean ordering it based on how many times each filter appears in the dataset. Is that what you want?

**Comment by linderr** [comment]
Sorry, i'm not being clear --- you can imagine this list as based off medical grade item first which does loosely go from N95, surgical masks, face shields, etc.

But we only very recently added "homemade masks" and "face shields - 3D printed/maker" to all of our FTM forms, globally. These DIY/non-medical grade can be thought of as "sub categories" to the first level of medical grade items. 

I am just suggesting all filter tiles (not just Canada) match the order we had decided for the Forms, collectively

**Comment by ngottlieb** [comment]
Yeah, I more or less get that, I just am questioning whether or not there is an actual reason for making this change. I think ordering by total number requested or alphabetically makes some sense for a user, but ordering by an arbitrary "we decided in this other venue that you probably haven't looked at" has no usability benefit and isn't a good use of developer time.

**Comment by linderr** [comment]
I understand this is a tweak and not a major thing lol. There are bigger things to do. We can leave this on GH until later.

**Comment by linderr** [comment]
Getting country zooms correct to maximize individual pin display, particularly on mobile where pinching/panning/zooming is not idea as @sumitsekhri just posted on #ux-designs is more immediate. [#564](https://github.com/findthemasks/findthemasks/issues/564)

**Comment by ngottlieb** [comment]
My point isn't just that it's a tweak, it's that I don't think this makes anything better for a user and it introduces a lot of complexity (it would mean we're maintaining *another* piece of data -- the order -- in two very separate places -- the forms and the code). 

Are you sure that ordering by total number requested or alphabetical doesn't make more sense? If I'm a user looking at this, I would expect to see similar things next to each other -- so alphabetical solves that problem. And, ordering by count would make the most important / common ones appear first, so that would also seem like a sensible choice. Ordering by the order that we put them on the forms is just an arbitrary order, there's no medical guideline we're following or anything. Moreover, people filtering by "What is being accepted" are most likely *not* people who have looked at the forms to begin with. They're donors, not recipients. So having it match another thing that they likely never see doesn't matter... Lastly, the filters are big text, all easily visible. Even on a country with the most filters, it's not laid out in a way that makes it hard for a user to find what they're looking for. I honestly don't think the order is important for usability.

I'm not being difficult just to be difficult. Introducing a hard coded order for these things means introducing unnecessary complexity to the code and unnecessary duplication of data (the order) that could easily fall out of sync. These things cost developer time not just now, when implementing, but at all points in the future whenever someone touches this code (or the forms). I've asked you what the UX case for this is, and you haven't really given one, so I really don't think we should do it.

**Comment by linderr** [comment]
haha I don't think you are being difficult this is just open discussion. I had a suggestion, you have a counterpoint, which I appreciate. 

I don't have a standard logic reason like alphabetic order and if we adopt that, I think it makes logical sense. However my gut feeling is still to include context to this problem and list N95s first, then the remaining tiles alphabetical order. N95s first is to highly the absolute most requested/limited PPE item worldwide and to capitalize on people's attention spans before they trail off scanning text and ultimately swiping/scrolling past the entire filter section items, state/provinces and all.

**Comment by ngottlieb** [comment]
So let's list by order of most requested by then?

I'm not saying we shouldn't use an order. I'm saying there's no point implementing an arbitrary order that increases complexity of maintenance and development when there's no case for that order improving usability. More broadly, I'm saying we shouldn't make changes, particularly ones that add maintenance difficulty, based on gut feeling, but rather on plausible arguments about whether or not they improve usability (preferably ones that are grounded in data like analytics).

**Comment by saikatbhadra** [comment]
The current equipment filters will be phased out with the new design (I believe it has a drop down). So let's not waste dev cycles on re-ordering the current UX and instead wait for the new design and make sure the order of the equipment follows some ordering that weighs:
- how much the equipment is requested i
- putting similar equipment near each other

Closing this for now, but lets make sure the new UX has a logical order.
