### ISSUE TITLE
Not all N95s are equal

### ISSUE THREAD

**Issue by mx00s** [findthemasks/findthemasks#82]
Earlier this week [Seattle Children's request for donations](https://m.facebook.com/story.php?story_fbid=10157320680637061&id=14517117060) said for 3M N95 masks they were accepting "1860, 1860s, and 1870". My unused 3M N95s from when the wildfire smoke was bad are the 8511 model.

I'm unclear whether any hospitals or clinics claiming to accept N95s will accept 8511 or any of the other models which aren't marketed for medical use. I want to donate the small number of masks I have directly to a reputable place where HCWs will use them, but at the same time I want to do it without contributing to communication bandwidth overload (see also #81).

Currently the Google Form has a checkbox for "N95s", but it could help to be more precise or at least encourage clarification in an open-ended field.

**Comment by r-pop** [comment]
This is a good question, I will refer it to our medical advisors. thank you.

**Comment by spitznagel** [comment]
It's a challenging question - it looks like some N95 masks are meant for industrial use, while others are also approved as "Surgical respirators":
https://www.cdc.gov/niosh/npptl/topics/respirators/disp_part/n95list1.html

The above list shows all masks approved as N95 masks, and marks in **bold** the ones that are also approved for surgical use.

The CDC offers additional details on the different approvals between N95 and N95 (for surgical) use here:
https://www.fda.gov/medical-devices/personal-protective-equipment-infection-control/n95-respirators-and-surgical-masks-face-masks

@r-pop - did our medical advisors get back to you? Depending on what they say, I suggest we resolve this issue by either:

**A) Adding links to the above clarifications on the CDC website for those who are curious (probably on the [Google Doc](https://docs.google.com/forms/d/e/1FAIpQLSfgCpK5coPVFC6rJrE7ZhimiZuDoEaL6fo6gYqxsN_FIpJZhg/viewform) as a link?)**

**B) Splitting the N95 category into two categories on the Google Doc:**
- N95 (rated for surgical use)
- N95 (general purpose)

Regardless, I suggest we change the description "N95s" on the Google Doc to be "N95 masks" because "N95s" is sometimes used by the FDA [on their website](https://www.fda.gov/medical-devices/personal-protective-equipment-infection-control/n95-respirators-and-surgical-masks-face-masks) to denote N95 masks that have the surgical designation:
![image](https://user-images.githubusercontent.com/8340647/77855361-cd3b1d00-71a4-11ea-8814-0dcfc841f1d6.png)

**Comment by spitznagel** [comment]
Merged into #340
