### ISSUE TITLE
Change counter copy from X requests to "Showing X of Y requests"

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#863]
Somehow the counter only shows what is displayed on the map view not arithmetic total per country/jurisdiction.

~~**Hacky fix:** zoom out appropriately to include everyone.~~
**Better fix:** zoom out to include geopolitical correct entities + change counter copy as @nburt suggests below

https://github.com/findthemasks/findthemasks/blob/master/client/locations-list-map.js#L616-L630

**Comment by nburt** [comment]
The counter is synced with the total number that are visible on the map. I'm not against zooming out the default views to be more inclusive of Hawaii / Alaska (for US at least) but another thought would to change the counter copy.

Rather than "X requesters" we could have something like "Showing X of Y requesters", could be a little clearer that they don't have the full country visible

**Comment by linderr** [comment]
That sounds great!

**Comment by linderr** [comment]
For both Find the Masks and Find the Makers:
**Masks:** X requesters --> X of Y requests
**Makers:** X Groups --> X of Y maker groups
