### ISSUE TITLE
Fix legacy browser issues with IE11

### ISSUE THREAD

**Issue by linderr** [findthemasks/findthemasks#986]
**FTM does not load on Internet Explore (white page + infinite wheel).**
Many hospitals and government (and labs) still use various non-Windows 10 Windows operating systems and default to IE.

**Here is the errors from the dev console:**
![image](https://user-images.githubusercontent.com/62862914/83292252-a007ec80-a19e-11ea-8d44-0a9bd440c6b5.png)

@awong-dev states the Syntax error is the issue
@ngottlieb muses this can be fixed with babel. We have `.babelrc` so that is a place to start

**Comment by smattingly** [comment]
FYI, the referenced column 38675 is the first appearance in that file of `class` *as a reserved word*.

My babel knowledge is minimal, but I see that we are on version 7.x with a .babelrc, and wonder if [this information](https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading) is relevant?  Tagging @ngottlieb since he was mentioned in connection with babel.

**Comment by linderr** [comment]
that's interesting, @smattingly I'm going to copy your comment into #dev as well for more visibility :)

**Comment by smattingly** [comment]
I downloaded IE 11 and confirmed that the code fetched from the production site contains class declarations. I assume that means that the babel transpile isn't happening.

**Comment by smattingly** [comment]
Progress! See PR #991.
